----------------------------------
Timestamp: 18:21:59.664
SELECT PCCLIENT.CODCLI, PCCLIENT.CLIENTE, PCCLIENT.FANTASIA, PCCLIENT.TELENT,
       PCCLIENT.ENDERENT, PCCLIENT.MUNICENT, PCCLIENT.CODUSUR1, PCUSUARI.NOME,
       PCATIVI.RAMO
FROM   PCCLIENT, PCUSUARI, PCATIVI
WHERE  PCCLIENT.CODUSUR1 = PCUSUARI.CODUSUR
AND    PCCLIENT.CODATV1  = PCATIVI.CODATIV
AND  PCCLIENT.CODCLI = :CODCLI
ORDER BY PCCLIENT.CLIENTE
CODCLI = '2'
----------------------------------
Timestamp: 18:22:22.232
SELECT PCEMPR.CODFILIAL 
FROM PCEMPR 
WHERE PCEMPR.MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:22:22.341
SELECT NUMMANIF,
       NUMSEQ,
       CODCLI,
       CONTATO,
       TELEFONE,
       MEIO,
       COMPORTAMENTO,
       SITUACAO,
       DTAB,
       DTRE,
       DTPR,
       DTSO,
       DTCO,
       DTRB,
       DTRT,
       CODFUNCAB,
       CODFUNCRE,
       CODFUNCPR,
       CODFUNCSO,
       CODFUNCCO,
       CODFUNCRB,
       CODFUNCRT,
       CODSETORRT,
       MANIFESTACAO,
       CODASSUNTO,
       CODSETORENVIAR,
       CODPROD,
       PROVIDENCIA,
       SOLUCAO,
       COMUNICADO,
       SATISFEITO,
       RECEPTOR,
       REABERTA,
       CARGO,
       TEMPODECORRIDO,
       CODFILIAL,
       NUMMANIFCOPIA,
       NUMSEQCOPIA,
       DTCP,
       CODSETORCP,
       CODFUNCCP,
       DTEXPIRA, 
       NUMNOTA,
       CODRCA,
       CODTRANSPORTADOR,
       CODMOTORISTA,
       CODAJUDANTE
  FROM PCMANIF
  WHERE NVL(PCMANIF.INTERNO,'N') = 'N'
----------------------------------
Timestamp: 18:22:22.403
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 42267
----------------------------------
Timestamp: 18:22:22.435
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 42
----------------------------------
Timestamp: 18:22:22.450
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4


 FROM PCMANASSUNTO, PCSETOR
WHERE PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
  AND PCMANASSUNTO.CODASSUNTO = :CODASSUNTO
ORDER BY CODASSUNTO
CODASSUNTO = 71
----------------------------------
Timestamp: 18:22:22.513
SELECT NVL(PADRAOCALLCENTER,'P') FROM PCCONSUM
----------------------------------
Timestamp: 18:22:22.528
SELECT CODIGO
  FROM PCFILIAL
 WHERE CODIGO <> '99'
 ORDER BY DECODE(LENGTh(CODIGO), 1, '0' || CODIGO, CODIGO)
----------------------------------
Timestamp: 18:22:22.560
SELECT DFSEQ_PCMANIF.NEXTVAL FROM DUAL
----------------------------------
Timestamp: 18:22:22.575
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 0
----------------------------------
Timestamp: 18:22:22.607
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 0
----------------------------------
Timestamp: 18:22:22.622
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:22:22.653
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 0
----------------------------------
Timestamp: 18:22:22.685
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:22:22.716
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 0
----------------------------------
Timestamp: 18:22:22.732
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:22:22.763
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:22:22.794
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:22:22.828
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:22:22.846
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:22:22.877
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:22:22.908
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4,
      PCMANASSUNTO.GERAAGENDA,
      NVL(Pcmanassunto.Obrigaqtde,'N') AS Obrigaqtde

FROM PCMANASSUNTO, PCEMPR PCEMPR1, PCEMPR PCEMPR2, PCEMPR PCEMPR3, PCEMPR PCEMPR4, PCSETOR
WHERE PCMANASSUNTO.CODFUNC1 = PCEMPR1.MATRICULA
AND   PCMANASSUNTO.CODFUNC2 = PCEMPR2.MATRICULA
AND   PCMANASSUNTO.CODFUNC3 = PCEMPR3.MATRICULA
AND   PCMANASSUNTO.CODFUNC4 = PCEMPR4.MATRICULA(+)
AND   PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
AND   NVL(PCMANASSUNTO.ATIVO,'S') = 'S'
ORDER BY PCMANASSUNTO.ASSUNTO
----------------------------------
Timestamp: 18:22:22.970
select DIRWINTHOR from PCCONSUM
----------------------------------
Timestamp: 18:22:51.787
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:22:51.803
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:22:51.834
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4


 FROM PCMANASSUNTO, PCSETOR
WHERE PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
  AND PCMANASSUNTO.CODASSUNTO = :CODASSUNTO
ORDER BY CODASSUNTO
CODASSUNTO = 50
----------------------------------
Timestamp: 18:24:51.602
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:24:51.663
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:24:51.678
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4


 FROM PCMANASSUNTO, PCSETOR
WHERE PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
  AND PCMANASSUNTO.CODASSUNTO = :CODASSUNTO
ORDER BY CODASSUNTO
CODASSUNTO = 50
----------------------------------
Timestamp: 18:24:55.266
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:24:55.333
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:24:55.382
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4


 FROM PCMANASSUNTO, PCSETOR
WHERE PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
  AND PCMANASSUNTO.CODASSUNTO = :CODASSUNTO
ORDER BY CODASSUNTO
CODASSUNTO = 50
----------------------------------
Timestamp: 18:25:18.427
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:25:18.515
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:25:18.562
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4


 FROM PCMANASSUNTO, PCSETOR
WHERE PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
  AND PCMANASSUNTO.CODASSUNTO = :CODASSUNTO
ORDER BY CODASSUNTO
CODASSUNTO = 50
----------------------------------
Timestamp: 18:26:36.409
Successful commit.
----------------------------------
Timestamp: 18:26:36.409
begin  :result := sys.dbms_transaction.local_transaction_id(true); end;
result = '16.28.803204'
----------------------------------
Timestamp: 18:26:36.440
begin  :result := sys.dbms_transaction.local_transaction_id; end;
result = '16.28.803204'
----------------------------------
Timestamp: 18:26:36.471
SELECT SYSDATE FROM DUAL
----------------------------------
Timestamp: 18:26:36.487
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:26:36.502
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:26:36.533
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4


 FROM PCMANASSUNTO, PCSETOR
WHERE PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
  AND PCMANASSUNTO.CODASSUNTO = :CODASSUNTO
ORDER BY CODASSUNTO
CODASSUNTO = 50
----------------------------------
Timestamp: 18:26:36.596
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:26:36.630
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:26:36.646
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4


 FROM PCMANASSUNTO, PCSETOR
WHERE PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
  AND PCMANASSUNTO.CODASSUNTO = :CODASSUNTO
ORDER BY CODASSUNTO
CODASSUNTO = 50
----------------------------------
Timestamp: 18:26:36.708
begin  :result := sys.dbms_transaction.local_transaction_id; end;
result = '16.28.803204'
----------------------------------
Timestamp: 18:26:36.740
begin  :result := sys.dbms_transaction.local_transaction_id; end;
result = '16.28.803204'
----------------------------------
Timestamp: 18:26:36.771
INSERT INTO PCMANIF
  (NUMMANIF, NUMSEQ, CODCLI, CONTATO, TELEFONE, MEIO, COMPORTAMENTO, SITUACAO, DTAB, DTRE, DTPR, DTSO, DTCO, DTRB, DTRT, 
CODFUNCAB, CODFUNCRE, CODFUNCPR, CODFUNCSO, CODFUNCCO, CODFUNCRB, CODFUNCRT, CODSETORRT, MANIFESTACAO, CODASSUNTO, 
CODSETORENVIAR, CODPROD, PROVIDENCIA, SOLUCAO, COMUNICADO, SATISFEITO, RECEPTOR, REABERTA, CARGO, TEMPODECORRIDO, CODFILIAL, 
NUMMANIFCOPIA, NUMSEQCOPIA, DTCP, CODSETORCP, CODFUNCCP, DTEXPIRA, NUMNOTA, CODMOTORISTA, CODRCA, CODTRANSPORTADOR, CODAJUDANTE)
VALUES
  (:NUMMANIF, :NUMSEQ, :CODCLI, :CONTATO, :TELEFONE, :MEIO, :COMPORTAMENTO, :SITUACAO, :DTAB, :DTRE, :DTPR, :DTSO, :DTCO, :DTRB,
 :DTRT, :CODFUNCAB, :CODFUNCRE, :CODFUNCPR, :CODFUNCSO, :CODFUNCCO, :CODFUNCRB, :CODFUNCRT, :CODSETORRT, :MANIFESTACAO, 
:CODASSUNTO, :CODSETORENVIAR, :CODPROD, :PROVIDENCIA, :SOLUCAO, :COMUNICADO, :SATISFEITO, :RECEPTOR, :REABERTA, :CARGO, 
:TEMPODECORRIDO, :CODFILIAL, :NUMMANIFCOPIA, :NUMSEQCOPIA, :DTCP, :CODSETORCP, :CODFUNCCP, :DTEXPIRA, :NUMNOTA, :CODMOTORISTA, 
:CODRCA, :CODTRANSPORTADOR, :CODAJUDANTE)
NUMMANIF = 38993
NUMSEQ = 0
CODCLI = 28308
CONTATO = <NULL>
TELEFONE = <NULL>
MEIO = <NULL>
COMPORTAMENTO = <NULL>
SITUACAO = 'AB'
DTAB = '04/01/2019 18:26:37'
DTRE = <NULL>
DTPR = <NULL>
DTSO = <NULL>
DTCO = <NULL>
DTRB = <NULL>
DTRT = <NULL>
CODFUNCAB = 13
CODFUNCRE = <NULL>
CODFUNCPR = <NULL>
CODFUNCSO = <NULL>
CODFUNCCO = <NULL>
CODFUNCRB = <NULL>
CODFUNCRT = <NULL>
CODSETORRT = <NULL>
MANIFESTACAO = 'TESTE'
CODASSUNTO = 50
CODSETORENVIAR = <NULL>
CODPROD = <NULL>
PROVIDENCIA = <NULL>
SOLUCAO = <NULL>
COMUNICADO = <NULL>
SATISFEITO = <NULL>
RECEPTOR = <NULL>
REABERTA = <NULL>
CARGO = '7'
TEMPODECORRIDO = <NULL>
CODFILIAL = '1'
NUMMANIFCOPIA = <NULL>
NUMSEQCOPIA = <NULL>
DTCP = <NULL>
CODSETORCP = <NULL>
CODFUNCCP = <NULL>
DTEXPIRA = <NULL>
NUMNOTA = <NULL>
CODMOTORISTA = <NULL>
CODRCA = <NULL>
CODTRANSPORTADOR = <NULL>
CODAJUDANTE = <NULL>
----------------------------------
Timestamp: 18:26:37.196
SELECT CLIENTE FROM PCCLIENT
WHERE CODCLI = :CODCLI
CODCLI = 28308
----------------------------------
Timestamp: 18:26:37.212
SELECT USUARIOBD FROM PCEMPR
WHERE  MATRICULA = :MATRICULA
MATRICULA = 13
----------------------------------
Timestamp: 18:26:37.245
SELECT PCMANASSUNTO.CODASSUNTO
      ,PCMANASSUNTO.ASSUNTO

      ,PCMANASSUNTO.CODSETOR
      ,PCSETOR.DESCRICAO

      ,PCMANASSUNTO.PRAZO1
      ,PCMANASSUNTO.PRAZO2
      ,PCMANASSUNTO.PRAZO3
      ,PCMANASSUNTO.PRAZO4
      ,PCMANASSUNTO.PRAZOSETOR

      ,PCMANASSUNTO.CODFUNC1
      ,PCMANASSUNTO.CODFUNC2
      ,PCMANASSUNTO.CODFUNC3
      ,PCMANASSUNTO.CODFUNC4

      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR1
         WHERE PCEMPR1.MATRICULA = PCMANASSUNTO.CODFUNC1) NOMEFUNC1
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR2
         WHERE PCEMPR2.MATRICULA = PCMANASSUNTO.CODFUNC2) NOMEFUNC2
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR3
         WHERE PCEMPR3.MATRICULA = PCMANASSUNTO.CODFUNC3) NOMEFUNC3
      ,(SELECT USUARIOBD
          FROM PCEMPR PCEMPR4
         WHERE PCEMPR4.MATRICULA = NVL(PCMANASSUNTO.CODFUNC4,0)) NOMEFUNC4


 FROM PCMANASSUNTO, PCSETOR
WHERE PCMANASSUNTO.CODSETOR = PCSETOR.CODSETOR(+)
  AND PCMANASSUNTO.CODASSUNTO = :CODASSUNTO
ORDER BY CODASSUNTO
CODASSUNTO = 50
----------------------------------
Timestamp: 18:26:37.308
Successful commit.
----------------------------------
Timestamp: 18:26:44.271
Successful rollback.